### ISSUE TITLE
地图坐标问题

### ISSUE THREAD

**Issue by Whales233** [gxgk/map#2]
修改地图坐标后，坐标点在地图不显示，切换到未修改可显示的类目，再次点击修改的坐标类目又可显示

**Comment by Whales233** [comment]
请求协助

**Comment by NullYing** [comment]
截个图

**Comment by Whales233** [comment]
https://drive.google.com/open?id=1mkUrrT8Wl8W_yaH6Z4eSVo7pJ93R6II7

**Comment by Whales233** [comment]
修改地图坐标后，坐标点不显示，切换到未修改可显示的类目，再点击修改的坐标类目又可显示
