### ISSUE TITLE
你好，我想请问一下

### ISSUE THREAD

**Issue by zzszms** [gxgk/map#4]
你好，我想请问一下，是不是你们这个地图的小程序，是无法获取到用户的信息的？

**Comment by dairoot** [comment]
我们不需要用户数据，所以就没有去获取用户的信息了。

**Comment by zzszms** [comment]
噢，原来是这样的。谢谢了啊。
然后我看了很多，应该也是用你们这个源码做的校园导览，还有你们的，为啥都将校园导览这个小程序单独分开？
为何不放到功能性的小程序中，当作一个功能呢？

**Comment by dairoot** [comment]
单独开来，方便他人使用和学习。现在小程序直接可以直接跳转，也可以当做一个小功能进行跳转。
