### ISSUE TITLE
点击标记点的bindmarkertap事情改变icon

### ISSUE THREAD

**Issue by lms200905** [gxgk/map#5]
想在贵校的这个校园导览基础上做一些更改，其中一个想做的是标记点的icon变化，当标记点被点击，icon变成其他的，研究了许久不知从哪里做改变，不知能否提点一二?

**Comment by NullYing** [comment]
看一下微信的map组件

**Comment by NullYing** [comment]
参考微信map组件，bindmarkertap属性，触发函数后更换icon就可以了
