### ISSUE TITLE
地图组件层级问题

### ISSUE THREAD

**Issue by Observer-L** [gxgk/map#6]
![909178512062053377](https://user-images.githubusercontent.com/28595171/47801188-9753f800-dd68-11e8-8dc2-869bb56bf970.jpg)
从**校园导览首页**切到**路径规划页**时，前者地图组件依旧显示但不可操作，后者被遮挡但可操作。

**Comment by dairoot** [comment]
手机问题？我们并没有该问题出现

**Comment by NullYing** [comment]
貌似是某个微信版本或者基础库版本会出现，我之前出现过之后什么都没改，过了一段时间就可以了

**Comment by Observer-L** [comment]
已解决，微信版本问题。
