### ISSUE TITLE
路线规划地址不对

### ISSUE THREAD

**Issue by ghost** [gxgk/map#7]
你好，我想问下为什么，实际搭建测试的过程中，路线规划地址不是从起点开始的，有什么办法解决吗？
![Screenshot_20190407-150237](https://user-images.githubusercontent.com/43264024/55679990-baea2280-5946-11e9-98c4-ac88df4e574b.jpg)

**Comment by dairoot** [comment]
描述清晰点，“路线规划地址不是从起点开始的”  是指定位不准？

**Comment by NullYing** [comment]
导航不可能在楼里面做起点的，任意一种导航软件都一样
